### ISSUE TITLE
Start Backend failed, Import for TConfig not found

### ISSUE THREAD

**Issue by UteHaus** [nextcloud/context_chat_backend#134]
**Describe the bug**
When the container start withe backend, in the main.py the import not found.

**To Reproduce**
1. Start the  context_chat_backend (Docker)

**Expected behavior**
The docker container with  context_chat_backend start without a exception/ import error
**Context Chat Backend logs (if applicable, from the docker container)**

```
    
    ModuleNotFoundError: No module named 'context_chat_backend.types'    
    Starting PostgreSQL...    
    pg_ctl: another server might be running; trying to start server anyway
    waiting for server to start.... done    
    server started    
    Waiting for PostgreSQL to start...    
    PostgreSQL is up and running.    
    CCB_DB_URL is already set. Skipping database setup.    
    Traceback (most recent call last):    
      File "/app/./main.py", line 10, in <module>    
        from context_chat_backend.types import TConfig  # isort: skip    
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
    ModuleNotFoundError: No module named 'context_chat_backend.types'

```

**Setup Details (please complete the following information):**
 - Nextcloud Version: 30.0.4
 - AppAPI Version:  4.0.3
 - Context Chat PHP Version (client) 4.0.2
 - Context Chat Backend Version 4.0.2
 - Nextcloud deployment method: Docker apache 
 - Chat Backend deployment method:Docker (build) 
- [config file (repo default for CPU)](https://github.com/nextcloud/context_chat_backend/blob/master/config.cpu.yaml)
**Additional context**
The same error occurs when I use the version 4.0.2 for the backend and client

Build command: ```docker build --no-cache -f Dockerfile -t context_chat_backend:${version} . ```
The Docker Compose:
```yaml
  context_chat_backend:
    image: context_chat_backend:4.0.2
    build: 
      context: ./context_chat_backend/repo/context_chat_backend
      dockerfile: Dockerfile
    ports:
      - "10034:10034"
    environment:
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./context_chat_backend/config.yaml:/app/config.yaml
      - ./context_chat_backend/data:/app/context_chat_backend
      - /var/run/docker.sock:/var/run/docker.sock
      - persistent_storage:/app/persistent_storage
    env_file:
      - .env
```
Run Docker:
```
docker compose build --pull
docker compose up -d 
``
