### ISSUE TITLE
Can not found GPU

### ISSUE THREAD

**Issue by aef5748** [nextcloud/context_chat_backend#69]
We deploy context_chat_backend with cpu is workable. To use gpu config.yaml, but it's not working.
How could I do to set gpu config or others way to solve it?
I've tried to set below action but it not working.
- Set n_gpu_layers: 10
- Set NVIDIA_VISIBLE_DEVICES=all and NVIDIA_DRIVER_CAPABILITIES=compute in docker-compose

My environment:
CUDA: 11.8
Nextcloud: 29.0.3
context_chat_backend: 2.2.1

<details>

<summary>docker-compose.yaml</summary>

```
version: '3.7'
networks:
  nextcloud:
    name: nextcloud
    driver: bridge
    
services:
  db:
    image: postgres:12-alpine
    container_name: Nextcloud-DB
    restart: always
    volumes:
      - /home/sw/Nextcloud/container/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - TZ=Asia/Taipei
    networks:
      - nextcloud

  app:
    image: nextcloud:29.0.3-apache
    container_name: Nextcloud
    restart: always
    ports:
      - 3000:80
    depends_on:
      - db
      - appapi
    volumes:
      - /home/sw/Nextcloud/container/web:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=db
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    networks:
      - nextcloud
      
  appapi:
    image: ghcr.io/cloud-py-api/nextcloud-appapi-dsp:v1.3.2
    container_name: nextcloud-appapi-dsp
    hostname: nextcloud-appapi-dsp
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NC_HAPROXY_PASSWORD=nextcloud
      - TIMEOUT_SERVER=1800s
      - TIMEOUT_CONNECT=300s
      - TIMEOUT_CLIENT=300s
    networks:
      - nextcloud

  backend:
    image: ghcr.io/nextcloud/context_chat_backend:2.2.1
    container_name: context_chat_backend
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/sw/Nextcloud/container/content/config.yaml:/app/config.yaml
      - /home/sw/Nextcloud/container/content/persistent_storage:/app/persistent_storage
      - /home/sw/Nextcloud/container/content/context_chat_backend:/app/context_chat_backend
    ports:
      - 10034:10034
    environment:
      - AA_VERSION=2.2.1
      - APP_VERSION=2.2.1
      - APP_SECRET=12345
      - APP_ID=context_chat_backend
      - APP_DISPLAY_NAME=Context Chat Backend
      - APP_HOST=0.0.0.0
      - APP_PORT=10034
      - APP_PERSISTENT_STORAGE=persistent_storage
      - NEXTCLOUD_URL=http://192.168.101.20:3000
      - TRANSFORMERS_OFFLINE=1
    networks:
      - nextcloud
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

</details>

detail log
[context_chat_backend_GPU_unsupported_20240911.txt](https://github.com/user-attachments/files/16961225/context_chat_backend_GPU_unsupported_20240911.txt)
