### ISSUE TITLE
[install-help]: Registration completed, but unable to ask questions

### ISSUE THREAD

**Issue by aef5748** [nextcloud/context_chat_backend#80]
Hi, 

My previous installation worked normally, but when I re-installed it on another computer, it appeared that I could register but could not ask questions.
The settings are all the same, I don’t know what happened. Could you help me to check it?

The versions used are as follows:
```
OS:ubuntu 20.04
Nextcloud: 30.0.0
Context Cat Backend: 3.0.2
Context Cat: 3.0.2
```

When asking a question, the following error message will pop up:
```
File "/usr/local/lib/python3.11/dist-packages/nc_py_api/_session.py", line 231, in ocs
    raise NextcloudException(status_code=ocs_meta["statuscode"], reason=ocs_meta["message"], info=info)
nc_py_api._exceptions.NextcloudException: [412] <request: POST /ocs/v1.php/taskprocessing/schedule>
```
detail log
[context_chat_3.0.2_issue_external_20240925.txt](https://github.com/user-attachments/files/17123189/context_chat_3.0.2_issue_external_20240925.txt)

<details>

<summary>docker-compose</summary>

```
version: '3.7'
networks:
  nextcloud:
    name: nextcloud
    driver: bridge
    
services:
  db:
    image: postgres:12-alpine
    container_name: Nextcloud-DB
    restart: always
    volumes:
      - /home/sw/Nextcloud/container/30/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - TZ=Asia/Taipei
    networks:
      - nextcloud

  app:
    image: nextcloud:30.0.0-apache
    container_name: Nextcloud
    restart: always
    ports:
      - 3000:80
    depends_on:
      - db
      - appapi
      - backend
    volumes:
      - /home/sw/Nextcloud/container/30/web:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=db
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    networks:
      - nextcloud
      
  appapi:
    image: ghcr.io/cloud-py-api/nextcloud-appapi-dsp:v1.3.2
    container_name: nextcloud-appapi-dsp
    hostname: nextcloud-appapi-dsp
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NC_HAPROXY_PASSWORD=nextcloud
      - TIMEOUT_SERVER=1800s
      - TIMEOUT_CONNECT=300s
      - TIMEOUT_CLIENT=300s
    networks:
      - nextcloud

  backend:
    image: ghcr.io/nextcloud/context_chat_backend:3.0.2
    container_name: context_chat_backend
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/sw/Nextcloud/container/content/config.yaml:/app/config.yaml
      - /home/sw/Nextcloud/container/context/persistent_storage:/app/persistent_storage
      - /home/sw/Nextcloud/container/context/context_chat_backend:/app/context_chat_backend
    ports:
      - 10034:10034
    environment:
      - AA_VERSION=2.7.0
      - APP_VERSION=3.0.2
      - APP_SECRET=12345
      - APP_ID=context_chat_backend
      - APP_DISPLAY_NAME=Context Chat Backend
      - APP_HOST=0.0.0.0
      - APP_PORT=10034
      - APP_PERSISTENT_STORAGE=persistent_storage
      - NEXTCLOUD_URL=http://192.168.2.6:3000
     # - TRANSFORMERS_OFFLINE=1
    networks:
      - nextcloud
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

</details>
